- name: Deploy Cephsfs
  hosts: node1
  #connection: local
  gather_facts: false
  become: true

  tasks:
    
    - name: Create Cephfs
      command: kubectl apply -f filesystem.yaml
    
    - name: Create StorageClass
      command: kubectl apply -f csi/cephfs/storageclass.yaml

    - name: List available classes
      command: kubectl get sc

    - name: Create test PVC and Pod
      command: kubectl create -f csi/cephfs/pvc.yaml
    
    - name: test usage of Persistent Volume
      command: kubectl get pvc

    - name: ???
      command: kubectl apply -f csi/cephfs/pod.yaml