- name: Deploy Cephsfs
  hosts: node1
  #connection: local
  gather_facts: false
  become: true

  vars:
    rook_dir: "{{ rook_dir }}"

  tasks:
    
    - name: Create Cephfs
      command: kubectl apply -f filesystem.yaml
      args:
        chdir: "{{ rook_dir }}/deploy/examples"
    
    - name: Create StorageClass
      command: kubectl apply -f storageclass.yaml
      args:
        chdir: "{{ rook_dir }}/deploy/examples/csi/cephfs"

    - name: List available classes
      command: kubectl get sc
      register: results
    - debug:
        var: result.stdout_lines

    - name: Create test PVC and Pod
      command: kubectl apply -f pvc.yaml
      args:
        chdir: "{{ rook_dir }}/deploy/examples/csi/cephfs"
    
    - name: test usage of Persistent Volume
      command: kubectl get pvc
      register: results
    - debug:
        var: result.stdout_lines

    - name: Create demo pod
      command: kubectl apply -f pod.yaml
      args:
        chdir: "{{ rook_dir }}/deploy/examples/csi/cephfs"