- name: Clean up deployment
  hosts: localhost
  #connection: local
  gather_facts: false
  become: true

  tasks:
    - name: Destroy virtual machines
      #command: terraform destroy

      openstack.cloud.server:
        name: vm-0
        state: absent
      openstack.cloud.server:
        name: vm-1
        state: absent
      openstack.cloud.server:
        name: vm-2
        state: absent