#Terraform for 4 VMs
- hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /Project-2-io2/tree/main/Vms
   
    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: /Project-2-io2/tree/main/Vms
      register: terraform