#Terraform for 4 VMs
- hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: Vms/VMs.tf
   
    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: Vms/VMs.tf
      register: terraform