#Terraform for 4 VMs
- hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: Vms/VMs.tf
   
    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: Vms/VMs.tf
      register: terraform
#Everything below here may be unnecesary
# gets ip adresses

    - name: Get instance IP address
      shell: 'terraform output instance_ip_address | tr -d \" '
      args:
        chdir: /home/ubuntu/web
      register: instance_ip_address

    - name: Get instance IP address
      shell: 'terraform output instance_ip_address2 | tr -d \" '
      args:
        chdir: /home/ubuntu/web
      register: instance_ip_address2

    - name: Get instance IP address
      shell: 'terraform output instance_ip_address3 | tr -d \" '
      args:
        chdir: /home/ubuntu/web
      register: instance_ip_address3

    - name: Get instance IP address
      shell: 'terraform output instance_ip_address4 | tr -d \" '
      args:
        chdir: /home/ubuntu/web
      register: instance_ip_address4

#Adds ips to dynamic gruoup
    - name: Add host to dynamic group
      add_host:
        name: "{{ instance_ip_address.stdout }}"
        groups: dynamic_hosts

    - name: Add host to dynamic group
      add_host:
        name: "{{ instance_ip_address2.stdout }}"
        groups: dynamic_hosts

    - name: Add host to dynamic group
      add_host:
        name: "{{ instance_ip_address3.stdout }}"
        groups: dynamic_hosts

    - name: Add host to dynamic group
      add_host:
        name: "{{ instance_ip_address4.stdout }}"
        groups: dynamic_hosts

#Wait for ssh to become availiable
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ instance_ip_address.stdout }}"
        port: 22
        delay: 10
        timeout: 120
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ instance_ip_address2.stdout }}"
        port: 22
        delay: 10
        timeout: 120
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ instance_ip_address3.stdout }}"
        port: 22
        delay: 10
        timeout: 120
      - name: Wait for SSH to become available
      wait_for:
        host: "{{ instance_ip_address4.stdout }}"
        port: 22
        delay: 10
        timeout: 120


    - name: Wait for system to be fully booted and ready for SSH
      wait_for:
        path: /var/run/nologin
        state: absent
        delay: 10
        timeout: 600